repositories:
  - name: zahori
    url: https://zahori-io.github.io/zahori-helm-charts

releases:
  - name: consul
    namespace: zahori
    chart: zahori/zahori-consul
    version: 1.0.0
    values:
      - values/consul.yaml
  - name: moon
    namespace: moon
    chart: zahori/zahori-moon
    version: 1.0.0
    needs:
      - zahori/consul
    values:
      - values/moon.yaml
  - name: postgresql
    namespace: zahori
    chart: zahori/zahori-postgresql
    version: 1.0.0
    values:
      - values/postgresql.yaml

  - name: server
    namespace: zahori
    chart: zahori/zahori-server
    version: 1.0.0
    needs:
      - zahori/postgresql
      - zahori/consul
      - moon/moon
    values:
      - values/server.yaml

  - name: scheduler
    namespace: zahori
    chart: zahori/zahori-scheduler
    version: 1.0.0
    needs:
      - zahori/postgresql
      - zahori/consul
      - moon/moon
      - zahori/server
    values:
      - values/scheduler.yaml

  - name: wikipedia-process
    namespace: zahori
    chart: zahori/zahori-process
    version: 1.0.0
    needs:
      - zahori/postgresql
      - zahori/consul
      - moon/moon
      - zahori/server
    values:
      - values/process.yaml
